baseURL = "/"
languageCode = "zh-cn"
defaultContentLanguage = "en"
title = "WindSing"                        # site title                     # 网站标题
theme = "zozo"
# theme = "kagome"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 100
paginate = 4                           # shows the number of articles   # 首页显示文章数量
enableEmoji = true
googleAnalytics = ""                   # your google analytics id       # Google统计代码
disqusShortname = ""                   # your discuss shortname         # Disqus评论系统代码

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true

[author]                               # essential                      # 必需
  name = "windsing"

[blackfriday]
  smartypants = false

[[menu.main]]                          # config your menu               # 配置菜单
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "归档"
  weight = 20
  identifier = "archive"
  url = "/posts/"
[[menu.main]]
  name = "标签"
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "读书"
  weight = 45
  identifier = "read"
  url = "/read/"  
[[menu.main]]
  name = "文档"
  weight = 40
  identifier = "doc"
  url = "http://doc.windsing.cn"  
[[menu.main]]
  name = "关于"
  weight = 50
  identifier = "about"
  # url = "/about/"
  url = "http://me.windsing.cn"

[params]
  subTitle = "Today my life begins!"                                       # site's subTitle              # 网站二级标题
  footerSlogan = "有朋自远方来!"                                            # site's footer slogan         # 网站页脚标语
  keywords = ["blog","windsing"]                                           # site's keywords              # 网站关键字
  description = "wind sing for me"                                         # site's description           # 网站描述
  enableMathJax = true                                                     # enable mathjax               # 是否使用mathjax（数学公式）
  enableSummary = true                                                     # display the article summary  # 是否显示文章摘要
  mainSections = ["posts","post"]
  
# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
[params.valine]
  enable = true
  appId = "LQ1zbiVVi2TX117q8HuHAHTr-gzGzoHsz"
  appKey = "vSh3Mo8NMWFlKeMdth9wJbHf"
  placeholder = ""
  visitor = true

# Your socail's url
# 社交地址配置
# 支持图标:https://remixicon.com/
[social]
    github = "https://github.com/786980206"

[params.info]
  qq = "786980206"
  email = "me@windsing.cn"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
